[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library = { path = "../library" }
slug = "0.1.5"
flume = "0.11.0"
image = "0.24.7"
simple_logger = "4.2.0"
log = "0.4.20"
