[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
image = "0.24.7"
log = "0.4.20"
serde = { version = "1.0.192", features = ["derive"] }
serde-binary = "0.5.0"
serde_cbor = "0.11.2"
serde_json = "1.0"
simple-log = "1.6.0"
