[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
library = { path = "../library" }
log = "0.4.20"
simple-log = "1.6.0"
simple_logger = "4.2.0"
