[default]
address = "172.17.0.1"
port = 8000
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
ip_header = "X-Real-IP" # set to `false` to disable
log_level = "normal"
cli_colors = true
secret_key = "hPrYyЭRiMyµ5sBB1π+CMæ1køFsåqKvBiQJxBVHQk="
temp_dir = "/tmp"
template_dir = "./webapp/templates/"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 10
mercy = 5
force = true